### PR TITLE
Checking CI  status for preservation status

### PR DESCRIPTION
**Pull request by tahiat**

### CODE REVIEW

**Review by kelloggm — COMMENTED** [review]
CI output looks good. Please add a preservation status json to the repo and then add a check against it, and then I will approve.

**Comment by LoiNguyenCS** [comment]
Wow, the output of the CI looks so promising. So we have 4/14 projects not passing the preservation test, and 2 of them are due to failing in minimization? Am I misunderstanding something here?

**Comment by tahiat** [comment]
> Wow, the output of the CI looks so promising. So we have 4/14 projects not passing the preservation test, and 2 of them are due to failing in minimization? Am I misunderstanding something here?

You are right.

**Comment by tahiat** [comment]
depends on https://github.com/tahiat/specimin-evaluation/pull/34

**Review by kelloggm — APPROVED** [review]
LGTM, thanks

**Pull request merged**
